### ISSUE TITLE
Distribute pre-compiled releases

### ISSUE THREAD

**Issue by MOZGIII** [DevinR528/cargo-sort#23]
I'd like this project to ship pre-compiled releases.

### Why?

We'd like to use this at CI, however, `cargo install` is much more costly than a single `wget` would be. Since CI is pretty much a constant repetition of the same scenario - it would be a ton of CPU cycles wasted if we compile `cargo-sort` every time.

### Proposal

Automation. Would be nice if there was a Github Action at this repo, that would, for each Github release, run the build from the relevant tag and upload the built artifact to the release artifacts.
Then everyone will be able to download the releases at CI, and it won't be a burden to maintain the releases up to date.

**Comment by DevinR528** [comment]
Good idea! Would you be interested in doing this? Otherwise, I can check it out in the next few days.

**Comment by MOZGIII** [comment]
I don't think I can take care of it, because it requires privileged repo access for debugging. I don't have a good source where I could suggest taking inspiration either. However, there are some blogs on the topic that might be helpful.

**Comment by DevinR528** [comment]
Oh yeah good point about debugging. I'll take a look in the next few days, thanks for the idea!

**Comment by DevinR528** [comment]
This worked out great, check it out https://github.com/DevinR528/cargo-sort/releases/tag/v1.0.5 if you have any problems just let me know. I did try out the linux bin but can't try any of the others, although not sure why they wouldn't work :shrug:

**Comment by MOZGIII** [comment]
Looks good! I'd consider it done, if I have issues with integration I'll let you know, but so far things look like expected.
