### ISSUE TITLE
Unsynchronised releases

### ISSUE THREAD

**Issue by grawlinson** [DevinR528/cargo-sort#30]
The releases for `cargo-sort` seem to out of sync, e.g. crates.io: `1.0.6`, GitHub releases/tags: `1.0.5`.

Any chance of a tag being uploaded? Thanks! :)

**Comment by DevinR528** [comment]
Oop good catch thanks! All the binaries should be there once CI generates them https://github.com/DevinR528/cargo-sort/releases/tag/v1.0.6
