### ISSUE TITLE
cargo install always reinstalls

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [DevinR528/cargo-sort#31]
Running `cargo install cargo-sort` when the tool is already up-to-date, re-compiles and re-installs.

Expected behavior: it should not re-install.

I think you're running into this issue: https://github.com/rust-lang/cargo/issues/8703.

This issue effectively disables using CI caching for this tool, since instead of re-using the existing cached install it will always re-install from scratch.

**Comment by DevinR528** [comment]
Thanks for the issue! Dang that stinks, I guess the best temporary fix until that issue is resolved would be to release the next N versions commenting out the fuzzing binary. Especially since it's just a convenience testing thing.

**Comment by DevinR528** [comment]
Just to double-check #32 would be the fix right? Then I'll bump some dependencies and cut a new release so we can make sure it actually fixes the problem.

**Comment by Mirko-von-Leipzig** [comment]
I think it will fix the issue; but I'm wondering if there isn't a different work-around that doesn't just rip out your fuzz target.

**Comment by DevinR528** [comment]
Hmm, I'm coming up with nothing. I googled around for workarounds but couldn't find any. I'll look around a few more days then probably just go with this, I don' t particularly mind having to uncomment it and I can add some better instruction in the `/src/fuzz.rs` file to uncomment and run for people?

**Comment by DevinR528** [comment]
Closed in #34 
If you are still having any problems with this let me know. Thanks!
