### ISSUE TITLE
README.md being discovered as Cargo.toml

### ISSUE THREAD

**Issue by iinuwa** [DevinR528/cargo-sort#33]
I think there might be something slightly off with Cargo.toml discovery.

Based on [this output](https://github.com/ruma/ruma/runs/4597703508?check_suite_focus=true#step:5:502) from Ruma's CI run, it looks like `cargo-sort` is trying to parse `examples/README.md` as a TOML file:

>  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TomlError { message: "TOML parse error at line 3, column 7\n  |\n3 | These are example projects showcasing how to use the various crates in this repository. You can use\n  |       ^\nUnexpected `a`\nExpected `=`\n" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-sort-1.0.6/src/sort.rs:113:46

In this workspace, subdirectories under `examples (`examples/*`) are set as workspace members. 
I'm not sure, but maybe the `examples` folder is being considered a workspace member instead of the subdirectories of `examples`, and then it's using the only file in that directory as the `Cargo.toml` file?

**Comment by ShadowJonathan** [comment]
I think it's raw-matching the glob `examples/*`, so maybe a bit smarter handling could solve that

**Comment by DevinR528** [comment]
Wow how did this not break before, so the glob iterator never sorted out files and the rest of the code expects a folder that has a `Cargo.toml` file in it.

**Comment by jplatte** [comment]
I see the cargo-sort issue was fixed and a new version released. I've restarted the CI job.

**Comment by iinuwa** [comment]
Thanks!
