### ISSUE TITLE
Let `-c` or some new flag take formatting into consideration

### ISSUE THREAD

**Issue by matze** [DevinR528/cargo-sort#40]
We use `cargo-sort` in CI to check if entries are sorted but it would also be super helpful to validate if it has been formatted correctly. I suppose making `-c` return a non-zero exit code would be a breaking change, so perhaps some other option would be necessary.

**Comment by DevinR528** [comment]
That would be nice, I'd be open to a PR adding the flag! Beware, the formatting feature is more a consequence of the toml looking terrible after sorting, so it may not be an exhaustive format check.
