### ISSUE TITLE
workspace.exclude seems to be ignored

### ISSUE THREAD

**Issue by jplatte** [DevinR528/cargo-sort#50]
In a cargo workspace, running `cargo sort --workspace` seems to use `workspace.members` to find directories with crates that belong to the workspace, without also checking `workspace.exclude` for ones that match a pattern in `workspace.members` but are not meant to be the workspace anyways.

**Comment by DevinR528** [comment]
Oh, it completely was, no question oops! Thanks for the catch. Fixed in #51.
