### ISSUE TITLE
make a cargo-sort-ck deprecation release

### ISSUE THREAD

**Issue by toxeus** [DevinR528/cargo-sort#58]
I'm using `cargo-sort-ck` in my CI pipelines. Only now I learned that it was renamed to `cargo-sort`. I would have been grateful if I would could have somehow learned about that earlier. 

One way to notify users stuck with `cargo-sort-ck` would be to make a new `cargo-sort-ck` release with a binary that prints some info about the rename and the link to https://crates.io/crates/cargo-sort and exits with a non-zero code. That would make the CI pipelines of those users fail and they would notice. 

Looking at the download stats from https://crates.io/crates/cargo-sort-ck it seems worth to notify those users.

**Comment by DevinR528** [comment]
Yeah, that's a really good idea! I would have never thought of that thanks! 
Should be done now, unless something odd happened with `cargo publish`

**Comment by toxeus** [comment]
It works! :+1: 
![image](https://user-images.githubusercontent.com/7702854/202197189-3db4fb3a-5caf-4c45-b2cc-83ad30d05c54.png)
