### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by hoijui** [DevinR528/cargo-sort#77]
Seeing that the last commit was 9 months ago, and many issues and PRs are ignored since well before that, I propose to add additional owners to this project, which could then address the PRs and issues, or add new owners if they become inactive too.
I also propose to create a fork of the project and view it as the new origin, if the above does not happen until one month from now, and @DevinR528 is not active again on this.

A list of potential, additional owners (authors of recent PRs):

- @Twey
- @ssrlive
- @eirenik0
- @dspicher
- @nipunn1313

**Comment by musjj** [comment]
I recommend just migrating to https://github.com/tamasfe/taplo tbh. The only difference is that taplo sorts all keys, not just dependencies.

**Comment by jplatte** [comment]
Hey! I didn't have notifications enabled for the repo, but I do now, and I have write access plus ownership on crates.io.

I tried publishing a v1.1.0 today, but unfortunately a bunch of things were broken by the `toml_edit` upgrade that was merged a few months ago.

I can continue to do some maintenance and publishing, but not put any work into fixing those new issues.

**Comment by hoijui** [comment]
eh wow.. cool @jplatte, thank you! :-)
So do you need a hand with the `toml_edit` stuff?
and if so, can you be more specific about what the problems are?

**Comment by ikrivosheev** [comment]
@hoijui can you close an issue?

**Comment by jplatte** [comment]
I can ;)
